name: triperry
description: "A travel assistant and trip planning application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.3.0
  path_provider: ^2.1.5
  url_launcher: ^6.2.5
  cupertino_icons: ^1.0.8
  google_generative_ai: ^0.4.6
  flutter_markdown: ^0.7.7
  smooth_page_indicator: ^1.2.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  shimmer: ^3.0.0
  intl: ^0.19.0
  flutter_animate: ^4.5.0
  lottie: ^3.0.0
  flutter_svg: ^2.0.9
  glassmorphism: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  flutter_chat_ui: ^1.6.8
  path: ^1.8.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
