// This file contains static Kenyan travel data, originally fetched from Google Maps API.
// Use this as a single source of truth for destinations, reviews, pricing, etc.

final List<Map<String, dynamic>> kenyaDestinations = [
  {
    'name': 'Maasai Mara National Reserve',
    'image': 'assets/images/kenya safari.jpeg',
    'description': 'World-famous for the Great Migration and Big Five safaris.',
    'price': 'From KES 12,000/day',
    'rating': 4.8,
    'reviews': 1523,
    'address': 'Narok, Kenya',
    'types': ['Wildlife', 'Safari', 'Nature'],
    'review_snippet': 'Unforgettable wildlife experience! Highly recommended.',
  },
  {
    'name': 'Diani Beach',
    'image': 'assets/images/diani beach.png',
    'description': 'Pristine white sands and turquoise waters on the Kenyan coast.',
    'price': 'From KES 9,500/night',
    'rating': 4.7,
    'reviews': 2104,
    'address': 'Kwale, Kenya',
    'types': ['Beach', 'Relaxation', 'Luxury'],
    'review_snippet': 'Best beach in Kenya! Great for families and couples.',
  },
  {
    'name': 'Mount Kenya',
    'image': 'assets/images/mount kenya.png',
    'description': 'Africa’s second highest peak, a UNESCO World Heritage Site.',
    'price': 'From KES 18,000/person',
    'rating': 4.6,
    'reviews': 987,
    'address': 'Mount Kenya National Park, Kenya',
    'types': ['Hiking', 'Adventure', 'Nature'],
    'review_snippet': 'Challenging climb, but the views are worth it!',
  },
  {
    'name': 'Nairobi National Park',
    'image': 'assets/images/nairobi city skyline.png',
    'description': 'Wildlife park on the edge of Nairobi city.',
    'price': 'From KES 4,000/person',
    'rating': 4.5,
    'reviews': 1345,
    'address': 'Nairobi, Kenya',
    'types': ['Wildlife', 'Safari', 'City'],
    'review_snippet': 'Amazing to see lions with the city skyline in the background.',
  },
  {
    'name': 'Lamu Old Town',
    'image': 'assets/images/lamu old town.png',
    'description': 'UNESCO World Heritage site with rich Swahili culture.',
    'price': 'From KES 7,500/day',
    'rating': 4.7,
    'reviews': 654,
    'address': 'Lamu, Kenya',
    'types': ['Culture', 'History', 'Beach'],
    'review_snippet': 'A step back in time. Beautiful architecture and friendly people.',
  },
  {
    'name': 'Hell’s Gate National Park',
    'image': 'assets/images/hells gorges.png',
    'description': 'Known for hiking, cycling, and dramatic gorges.',
    'price': 'From KES 3,000/person',
    'rating': 4.4,
    'reviews': 812,
    'address': 'Naivasha, Kenya',
    'types': ['Hiking', 'Adventure', 'Nature'],
    'review_snippet': 'Great for outdoor lovers. You can walk or bike among animals!',
  },
  {
    'name': 'Watamu Beach',
    'image': 'assets/images/watamu beach.png',
    'description': 'Marine park, coral reefs, and turtle conservation.',
    'price': 'From KES 8,000/night',
    'rating': 4.6,
    'reviews': 1102,
    'address': 'Watamu, Kenya',
    'types': ['Beach', 'Marine', 'Nature'],
    'review_snippet': 'Crystal clear water and amazing marine life.',
  },
  {
    'name': 'Fort Jesus',
    'image': 'assets/images/fort jesus.png',
    'description': 'Historic fort in Mombasa, built by the Portuguese in the 16th century.',
    'price': 'From KES 1,500/person',
    'rating': 4.5,
    'reviews': 789,
    'address': 'Mombasa, Kenya',
    'types': ['History', 'Culture', 'Museum'],
    'review_snippet': 'Fascinating history and great views of the old port.',
  },
  {
    'name': 'Karura Forest',
    'image': 'assets/images/karura waterfall.png',
    'description': 'Urban forest with walking trails, waterfalls, and picnic sites.',
    'price': 'From KES 500/person',
    'rating': 4.8,
    'reviews': 432,
    'address': 'Nairobi, Kenya',
    'types': ['Nature', 'Hiking', 'Picnic'],
    'review_snippet': 'Peaceful escape in the city. Perfect for a morning walk.',
  },
  {
    'name': 'Lake Naivasha',
    'image': 'assets/images/l naivasha with eaagle.png',
    'description': 'Freshwater lake with hippos, birds, and boat rides.',
    'price': 'From KES 2,500/person',
    'rating': 4.6,
    'reviews': 678,
    'address': 'Naivasha, Kenya',
    'types': ['Nature', 'Wildlife', 'Boat'],
    'review_snippet': 'Saw so many hippos and birds! The boat ride was a highlight.',
  },
];
