import 'package:flutter/material.dart';

/// Shows a dialog with saved AI travel recommendations
void showSavedRecommendations(BuildContext context) {
  showDialog(
    context: context,
    builder: (BuildContext context) {
      return AlertDialog(
        title: const Text('Saved Recommendations'),
        content: SizedBox(
          width: double.maxFinite,
          child: ListView(
            shrinkWrap: true,
            children: [
              ListTile(
                title: const Text('Tokyo City Guide'),
                subtitle: const Text('Created on April 18, 2025'),
                trailing: const Icon(Icons.chevron_right),
                onTap: () {
                  // View saved recommendation
                  Navigator.pop(context);
                  _showRecommendationDetails(context, 'Tokyo City Guide');
                },
              ),
              ListTile(
                title: const Text('Beach Vacation Ideas'),
                subtitle: const Text('Created on April 15, 2025'),
                trailing: const Icon(Icons.chevron_right),
                onTap: () {
                  // View saved recommendation
                  Navigator.pop(context);
                  _showRecommendationDetails(context, 'Beach Vacation Ideas');
                },
              ),
              ListTile(
                title: const Text('European Adventure'),
                subtitle: const Text('Created on April 10, 2025'),
                trailing: const Icon(Icons.chevron_right),
                onTap: () {
                  // View saved recommendation
                  Navigator.pop(context);
                  _showRecommendationDetails(context, 'European Adventure');
                },
              ),
            ],
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Close'),
          ),
        ],
      );
    },
  );
}

/// Shows details about a specific recommendation
void _showRecommendationDetails(BuildContext context, String title) {
  showDialog(
    context: context,
    builder: (BuildContext context) {
      return AlertDialog(
        title: Text(title),
        content: SizedBox(
          width: double.maxFinite,
          child: SingleChildScrollView(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              mainAxisSize: MainAxisSize.min,
              children: [
                Text('Generated by AI Assistant', 
                  style: Theme.of(context).textTheme.bodySmall?.copyWith(color: Colors.grey)),
                const SizedBox(height: 16),
                const Text('This personalized travel recommendation includes accommodations, activities, and dining suggestions based on your preferences.'),
                const SizedBox(height: 16),
                const Text('Recommendation Highlights:', 
                  style: TextStyle(fontWeight: FontWeight.bold)),
                const SizedBox(height: 8),
                const ListTile(
                  contentPadding: EdgeInsets.zero,
                  leading: Icon(Icons.hotel),
                  title: Text('Boutique Hotel'),
                  subtitle: Text('Centrally located, 4-star accommodations'),
                ),
                const ListTile(
                  contentPadding: EdgeInsets.zero,
                  leading: Icon(Icons.directions_walk),
                  title: Text('Guided Walking Tour'),
                  subtitle: Text('Historical sites and hidden gems'),
                ),
                const ListTile(
                  contentPadding: EdgeInsets.zero,
                  leading: Icon(Icons.restaurant),
                  title: Text('Local Cuisine'),
                  subtitle: Text('Traditional and fusion dining experiences'),
                ),
                const SizedBox(height: 16),
                const Text('Travel Dates: September 15-22, 2025'),
                const SizedBox(height: 8),
                const Text('Budget Range: \$1,500 - \$2,300'),
              ],
            ),
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Back'),
          ),
          TextButton(
            onPressed: () {
              Navigator.pop(context);
              ScaffoldMessenger.of(context).showSnackBar(
                const SnackBar(
                  content: Text('Added to My Trips!'),
                  behavior: SnackBarBehavior.floating,
                ),
              );
            },
            child: const Text('Add to My Trips'),
          ),
        ],
      );
    },
  );
}